'color':
        'variable':
                'Biomass': 'lightgreen'
                'Biomass Non-Commercial': 'darkgreen'
                'Coal Domestic': 'brown'
                'Coal Import': 'maroon'
                'Gas Domestic': 'lightblue'
                'Gas Import': 'darkblue'
                'Hydro': 'plum'
                'Nuclear Domestic': 'red'
                'Nuclear Import': 'darksalmon'
                'Oil Domestic': 'black'
                'Oil Import': 'grey'
                'Solar': 'yellow'
                'Wind': 'ivory'
                'Coal': 'black'
                'Gas Conventional': 'lightblue'
                'Gas Unconventional': 'darkblue'
                'Oil Conventional': 'grey'
                'Oil Unconventional': 'lightgrey'
                'Uranium': 'violet'
                'Agriculture': 'darkgreen'
                'Commercial HW': 'orange'
                'Commercial Other': 'violet'
                'Industry Specific': 'blue'
                'Industry Thermal': 'darkblue'
                'Residential Cooking': 'red'
                'Residential Hotwater': 'pink'
                'Residential Other': 'purple'
                'Transportation Freight': 'olive'
                'Transportation Passenger': 'black'
                'Coal USC CCS': 'grey'
                'IGCC CCS': 'blue'
                'Coal SC': 'brown'
                'Coal SubC': 'black'
                'Coal USC': 'lightgrey'
                'IGCC': 'violet'
                'Gas CC CCS': 'lightblue'
                'Gas CC peak': 'green'
                'Gas CC': 'magenta'
                'Hydro': 'aqua'
                'Nuclear PHWR': 'plum'
                'Solar CSP': 'yellow'
                'Solar PV': 'orange'
                'Wind Offshore': 'white'
                'Wind Onshore': 'olive'
                'IWT Oil': 'black'
                'Imports': 'Purple'